import { CATEGORIES, LOCATIONS, SORT_ORDERS, SORTS } from "./gatherings";

export const PAGINATION_CONFIG = {
  ITEMS_PER_PAGE: 12,
};

export const MOIM_LIST_DEFAULT_CONFIG = {
  CATE: CATEGORIES.ALL,
  SUB_CATE: "ALL",
  LOCATIONS: LOCATIONS.ALL,
  SORT: SORTS.UPDATE_AT,
  ORDER: SORT_ORDERS.DESC,
};
