export const CATEGORIES = {
  ALL: "ALL",
  RECOMMEND: "RECOMMEND",
  CULTURE: "CULTURE",
  FOOD: "FOOD",
  SPORTS: "SPORTS",
  HOBBY: "HOBBY",
  TRAVEL: "TRAVEL",
  STUDY: "STUDY",
  MEETING: "MEETING",
} as const;

export const LOCATIONS = {
  ALL: "ALL",
  ONLINE: "ONLINE",
  SEOUL: "SEOUL",
  BUSAN: "BUSAN",
  DAEGU: "DAEGU",
  INCHEON: "INCHEON",
  GWANGJU: "GWANGJU",
  DAEJEON: "DAEJEON",
  ULSAN: "ULSAN",
  SEJONG: "SEJONG",
  GYEONGGI: "GYEONGGI",
  GANGWON: "GANGWON",
  CHUNGCHEONGBUK: "CHUNGCHEONGBUK",
  CHUNGCHEONGNAM: "CHUNGCHEONGNAM",
  JEONBUK: "JEONBUK",
  JEOLLANAM: "JEOLLANAM",
  GYEONGSANGBUK: "GYEONGSANGBUK",
  GYEONGNAM: "GYEONGNAM",
  JEJU: "JEJU",
} as const;

export const SORTS = {
  UPDATE_AT: "UPDATE_AT",
  PARTICIPANT_COUNT: "PARTICIPANT_COUNT",
  SCORE: "SCORE",
} as const;

export const SORT_ORDERS = {
  DESC: "DESC",
  ASC: "ASC",
} as const;
